### ISSUE TITLE
Won't run in Unity 5: "The referenced script on this Behavior is missing"

### ISSUE THREAD

**Issue by Domiii** [stormtek/unity-rts-demo#6]
1. I get a lot of warnings of the kind "The referenced script on this Behavior is missing", which is probably causing all the other errors.
2. The Players' `Hud` objects are not initialized correctly.
3. If I add a `Hud` component to each player, more errors come up.

**Comment by stormtek** [comment]
I have not played around with Unity 5 yet, and this project is not officially supported for Unity 5 either.

**Comment by Domiii** [comment]
Maybe you want to add that to the README, then close this as `wont-fix`?
